const ALERT = 'ALERT'
const NOTIFICATION = 'NOTIFICATION'
const REFETCH_CHATS = 'REFETCH_CHATS'
const NEW_MESSAGE = 'NEW_MESSAGE'
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'
const NEW_ATTACHMENTS = 'NEW_ATTACHMENTS'

export {
  ALERT,
  NOTIFICATION,
  NEW_MESSAGE,
  REFETCH_CHATS,
  NEW_ATTACHMENTS,
  NEW_MESSAGE_ALERT,
}
